import fs from 'fs';
import path from 'path';

const firstNamesId = [
  'Budi',
  'Siti',
  'Adi',
  'Dewi',
  'Rizky',
  'Hendra',
  'Ani',
  'Agus',
  'Maya',
  'Dian',
  'Fajar',
  'Rina',
  'Eko',
  'Indah',
  'Bambang',
  'Novi',
  'Tri',
  'Lestari',
  'Ahmad',
  'Nur',
  'Doni',
  'Fitri',
  'Aris',
  'Wulan',
  'Joko',
  'Sri',
  'Taufik',
  'Retno',
  'Arif',
  'Ratna',
  'Bayu',
  'Yuni',
  'Dimas',
  'Mega',
  'Rahmat',
  'Sari',
  'Dedi',
  'Utami',
  'Irfan',
  'Putri',
];
const lastNamesId = [
  'Santoso',
  'Rahma',
  'Wijaya',
  'Lestari',
  'Pratama',
  'Gunawan',
  'Suryani',
  'Setiawan',
  'Indah',
  'Permata',
  'Hidayat',
  'Saputra',
  'Kusuma',
  'Utomo',
  'Nugroho',
  'Wibowo',
  'Subagyo',
  'Firmansyah',
  'Handoko',
  'Kurniawan',
  'Suharto',
  'Purwanto',
  'Susanto',
  'Budiman',
  'Hermawan',
  'Prasetyo',
  'Ramadhan',
  'Siregar',
  'Nasution',
  'Hutapea',
];

const firstNamesEn = [
  'Sarah',
  'Michael',
  'Emily',
  'David',
  'Jessica',
  'Robert',
  'Amanda',
  'Chris',
  'Daniel',
  'Sophia',
  'Alex',
  'Olivia',
  'James',
  'Emma',
  'Noah',
  'Isabella',
  'Lucas',
  'Ethan',
  'Charlotte',
  'Mason',
  'Liam',
  'Ava',
  'Benjamin',
  'Mia',
  'Henry',
  'Harper',
  'Alexander',
  'Evelyn',
  'William',
  'Abigail',
  'Oliver',
  'Emily',
  'Sebastian',
  'Elizabeth',
  'Jack',
];
const lastNamesEn = [
  'Johnson',
  'Chen',
  'Rodriguez',
  'Kim',
  'Taylor',
  'Martinez',
  'Wilson',
  'Thompson',
  'Lee',
  'Garcia',
  'Turner',
  'Smith',
  'Wilson',
  'Davis',
  'Miller',
  'Anderson',
  'Thomas',
  'Jackson',
  'White',
  'Harris',
  'Martin',
  'Clark',
  'Lewis',
  'Robinson',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Scott',
  'Torres',
  'Nguyen',
  'Hill',
];

const departments = ['IT', 'HR', 'Finance', 'Marketing', 'Sales', 'Operation', 'Support'];
const branches = ['Jakarta', 'Bandung', 'Surabaya', 'Medan', 'Makassar', 'Semarang'];

const positions = {
  IT: [
    'Senior Software Engineer',
    'DevOps Engineer',
    'Frontend Developer',
    'Backend Developer',
    'QA Automation Engineer',
    'System Administrator',
  ],
  HR: ['HR Specialist', 'Talent Acquisition Lead', 'People Operations Manager', 'HR Generalist', 'Recruiter'],
  Finance: ['Financial Analyst', 'Senior Accountant', 'Payroll Specialist', 'Finance Manager', 'Tax Officer'],
  Marketing: ['Content Strategist', 'SEO Specialist', 'Marketing Manager', 'Social Media Executive', 'Growth Marketer'],
  Sales: ['Account Executive', 'Sales Manager', 'Business Development Representative', 'Key Account Specialist'],
  Operation: ['Operations Coordinator', 'Logistics Manager', 'Process Specialist', 'Operations Manager'],
  Support: ['Customer Support Specialist', 'Support Team Lead', 'Technical Support Engineer', 'Helpdesk Agent'],
};

const femaleNames = new Set([
  'Sarah',
  'Emily',
  'Jessica',
  'Sophia',
  'Olivia',
  'Emma',
  'Isabella',
  'Charlotte',
  'Ava',
  'Mia',
  'Harper',
  'Evelyn',
  'Abigail',
  'Elizabeth',
  'Siti',
  'Ani',
  'Maya',
  'Dian',
  'Rina',
  'Indah',
  'Novi',
  'Lestari',
  'Fitri',
  'Wulan',
  'Retno',
  'Ratna',
  'Yuni',
  'Mega',
  'Sari',
  'Utami',
  'Putri',
]);

function generate250Users() {
  const users = [
    {
      id: 1,
      uuid: 'c9a4b2f1-6789-4e31-89ab-111111111111',
      employee_id: 'EMP-1001',
      full_name: 'Sarah Johnson',
      first_name: 'Sarah',
      last_name: 'Johnson',
      email: 'sarah.j@example.com',
      phone: '+62 812-3456-7891',
      avatar: 'https://i.pravatar.cc/150?u=sarah',
      gender: 'female',
      role: 'Admin',
      department: 'IT',
      branch: 'Jakarta',
      position: 'System Administrator',
      status: 'Active',
      joined_at: 'Jan 15, 2024',
      last_login: '2024-07-25T14:30:00Z',
      last_activity: 'Just now',
      created_at: '2024-01-15T08:00:00Z',
      updated_at: '2024-07-25T14:30:00Z',
      role_color: 'danger',
      status_color: 'success',
      permissions: ['users.create', 'users.read', 'users.update', 'users.delete', 'settings.manage'],
      is_online: true,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 2,
      uuid: 'd8b3c1e2-5678-4f22-90bc-222222222222',
      employee_id: 'EMP-1002',
      full_name: 'Michael Chen',
      first_name: 'Michael',
      last_name: 'Chen',
      email: 'm.chen@example.com',
      phone: '+62 813-4567-8902',
      avatar: 'https://i.pravatar.cc/150?u=michael',
      gender: 'male',
      role: 'Manager',
      department: 'IT',
      branch: 'Surabaya',
      position: 'Engineering Manager',
      status: 'Active',
      joined_at: 'Feb 12, 2024',
      last_login: '2024-07-25T14:25:00Z',
      last_activity: '5 mins ago',
      created_at: '2024-02-12T08:00:00Z',
      updated_at: '2024-07-25T14:25:00Z',
      role_color: 'warning',
      status_color: 'success',
      permissions: ['users.read', 'users.update', 'reports.view'],
      is_online: true,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 3,
      uuid: 'e7a2d3f4-4567-4a11-81cd-333333333333',
      employee_id: 'EMP-1003',
      full_name: 'Emily Rodriguez',
      first_name: 'Emily',
      last_name: 'Rodriguez',
      email: 'emily@example.com',
      phone: '+62 814-5678-9013',
      avatar: 'https://i.pravatar.cc/150?u=emily',
      gender: 'female',
      role: 'User',
      department: 'Marketing',
      branch: 'Bandung',
      position: 'Product Designer',
      status: 'Active',
      joined_at: 'Mar 12, 2024',
      last_login: '2024-07-25T12:30:00Z',
      last_activity: '2 hours ago',
      created_at: '2024-03-12T08:00:00Z',
      updated_at: '2024-07-25T12:30:00Z',
      role_color: 'primary',
      status_color: 'success',
      permissions: ['users.read', 'profile.update'],
      is_online: false,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 4,
      uuid: 'f6b1e4a5-3456-4b22-92de-444444444444',
      employee_id: 'EMP-1004',
      full_name: 'David Kim',
      first_name: 'David',
      last_name: 'Kim',
      email: 'd.kim@example.com',
      phone: '+62 815-6789-0124',
      avatar: 'https://i.pravatar.cc/150?u=david',
      gender: 'male',
      role: 'User',
      department: 'Marketing',
      branch: 'Jakarta',
      position: 'SEO Specialist',
      status: 'Inactive',
      joined_at: 'Jun 25, 2024',
      last_login: '2024-07-20T10:00:00Z',
      last_activity: '5 days ago',
      created_at: '2024-06-25T08:00:00Z',
      updated_at: '2024-07-20T10:00:00Z',
      role_color: 'primary',
      status_color: 'secondary',
      permissions: ['users.read'],
      is_online: false,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 5,
      uuid: 'a5c0f5b6-2345-4c33-83ef-555555555555',
      employee_id: 'EMP-1005',
      full_name: 'Jessica Taylor',
      first_name: 'Jessica',
      last_name: 'Taylor',
      email: 'j.taylor@example.com',
      phone: '+62 816-7890-1235',
      avatar: 'https://i.pravatar.cc/150?u=jessica',
      gender: 'female',
      role: 'Manager',
      department: 'HR',
      branch: 'Medan',
      position: 'HR Manager',
      status: 'Active',
      joined_at: 'Oct 5, 2023',
      last_login: '2024-07-25T13:30:00Z',
      last_activity: '1 hour ago',
      created_at: '2023-10-05T08:00:00Z',
      updated_at: '2024-07-25T13:30:00Z',
      role_color: 'warning',
      status_color: 'success',
      permissions: ['users.read', 'users.update', 'reports.view'],
      is_online: false,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 6,
      uuid: 'b4d9a6c7-1234-4d44-94fa-666666666666',
      employee_id: 'EMP-1006',
      full_name: 'Robert Martinez',
      first_name: 'Robert',
      last_name: 'Martinez',
      email: 'r.martinez@example.com',
      phone: '+62 817-8901-2346',
      avatar: 'https://i.pravatar.cc/150?u=robert',
      gender: 'male',
      role: 'User',
      department: 'Finance',
      branch: 'Makassar',
      position: 'Senior Accountant',
      status: 'Active',
      joined_at: 'Apr 19, 2024',
      last_login: '2024-07-25T14:00:00Z',
      last_activity: '30 mins ago',
      created_at: '2024-04-19T08:00:00Z',
      updated_at: '2024-07-25T14:00:00Z',
      role_color: 'primary',
      status_color: 'success',
      permissions: ['users.read'],
      is_online: true,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 7,
      uuid: 'c3e8b7d8-0123-4e55-85ab-777777777777',
      employee_id: 'EMP-1007',
      full_name: 'Amanda Wilson',
      first_name: 'Amanda',
      last_name: 'Wilson',
      email: 'a.wilson@example.com',
      phone: '+62 818-9012-3457',
      avatar: 'https://i.pravatar.cc/150?u=amanda',
      gender: 'female',
      role: 'User',
      department: 'Operation',
      branch: 'Semarang',
      position: 'Operations Specialist',
      status: 'Pending',
      joined_at: 'May 2, 2024',
      last_login: null,
      last_activity: 'Never',
      created_at: '2024-05-02T08:00:00Z',
      updated_at: '2024-05-02T08:00:00Z',
      role_color: 'primary',
      status_color: 'warning',
      permissions: ['users.read'],
      is_online: false,
      action: ['view', 'edit', 'delete'],
    },
    {
      id: 8,
      uuid: 'd2f7c8e9-9012-4f66-96bc-888888888888',
      employee_id: 'EMP-1008',
      full_name: 'Chris Thompson',
      first_name: 'Chris',
      last_name: 'Thompson',
      email: 'c.thompson@example.com',
      phone: '+62 819-0123-4568',
      avatar: 'https://i.pravatar.cc/150?u=chris',
      gender: 'male',
      role: 'Admin',
      department: 'IT',
      branch: 'Jakarta',
      position: 'Security Administrator',
      status: 'Active',
      joined_at: 'Nov 30, 2023',
      last_login: '2024-07-25T14:15:00Z',
      last_activity: '15 mins ago',
      created_at: '2023-11-30T08:00:00Z',
      updated_at: '2024-07-25T14:15:00Z',
      role_color: 'danger',
      status_color: 'success',
      permissions: ['users.create', 'users.read', 'users.update', 'users.delete'],
      is_online: true,
      action: ['view', 'edit', 'delete'],
    },
  ];

  const remainingStatuses = [...Array(180).fill('Active'), ...Array(25).fill('Pending'), ...Array(37).fill('Inactive')];

  const roleOptions = [
    { role: 'Admin', role_color: 'danger', perms: ['users.create', 'users.read', 'users.update', 'users.delete'] },
    { role: 'Manager', role_color: 'warning', perms: ['users.read', 'users.update', 'reports.view'] },
    { role: 'Supervisor', role_color: 'info', perms: ['users.read', 'users.update'] },
    { role: 'User', role_color: 'primary', perms: ['users.read', 'profile.update'] },
  ];

  const activeActivities = ['Just now', '5 mins ago', '15 mins ago', '30 mins ago', '1 hour ago', '2 hours ago'];
  const inactiveActivities = ['Yesterday', '3 days ago', '5 days ago', '1 week ago'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  for (let i = 9; i <= 250; i++) {
    const isId = i % 2 === 1;
    const fnList = isId ? firstNamesId : firstNamesEn;
    const lnList = isId ? lastNamesId : lastNamesEn;

    const fn = fnList[(i * 3) % fnList.length];
    const ln = lnList[(i * 7) % lnList.length];
    const fullName = `${fn} ${ln}`;

    const cleanFn = fn.toLowerCase().replace(/ /g, '');
    const cleanLn = ln.toLowerCase().replace(/ /g, '');
    const domain = isId ? 'company.co.id' : 'example.com';
    const email = `${cleanFn}.${cleanLn}${i}@${domain}`;

    const status = remainingStatuses[i - 9];
    let statusColor = 'success';
    let lastActivity = 'Just now';
    let isOnline = false;

    if (status === 'Active') {
      statusColor = 'success';
      lastActivity = activeActivities[i % activeActivities.length];
      isOnline = lastActivity === 'Just now' || lastActivity === '5 mins ago';
    } else if (status === 'Pending') {
      statusColor = 'warning';
      lastActivity = 'Never';
      isOnline = false;
    } else {
      statusColor = 'secondary';
      lastActivity = inactiveActivities[i % inactiveActivities.length];
      isOnline = false;
    }

    const roleObj = roleOptions[i % roleOptions.length];
    const dept = departments[i % departments.length];
    const posList = positions[dept];
    const pos = posList[i % posList.length];
    const branch = branches[i % branches.length];

    const year = 2022 + (i % 3);
    const month = months[i % 12];
    const day = 1 + (i % 27);
    const joinedAt = `${month} ${day < 10 ? '0' + day : day}, ${year}`;

    users.push({
      id: i,
      uuid: `u${i}00000-0000-4000-8000-${String(i).padStart(12, '0')}`,
      employee_id: `EMP-${1000 + i}`,
      full_name: fullName,
      first_name: fn,
      last_name: ln,
      email: email,
      phone: `+62 8${10 + (i % 80)}-${1000 + ((i * 17) % 9000)}-${1000 + ((i * 23) % 9000)}`,
      avatar: `https://i.pravatar.cc/150?u=${i}`,
      gender: femaleNames.has(fn) ? 'female' : 'male',
      role: roleObj.role,
      department: dept,
      branch: branch,
      position: pos,
      status: status,
      joined_at: joinedAt,
      last_login: status !== 'Pending' ? '2024-07-25T10:00:00Z' : null,
      last_activity: lastActivity,
      created_at: '2024-01-01T08:00:00Z',
      updated_at: '2024-07-25T10:00:00Z',
      role_color: roleObj.role_color,
      status_color: statusColor,
      permissions: roleObj.perms,
      is_online: isOnline,
      action: ['view', 'edit', 'delete'],
    });
  }

  const activeCount = users.filter((u) => u.status === 'Active').length;
  const pendingCount = users.filter((u) => u.status === 'Pending').length;
  const inactiveCount = users.filter((u) => u.status === 'Inactive').length;

  return {
    success: true,
    message: 'Users retrieved successfully.',
    data: {
      summary: {
        total_users: users.length,
        active: activeCount,
        pending: pendingCount,
        inactive: inactiveCount,
        growth: '+18 this month',
        engagement: '75% engagement',
        onboarding: 'Needs onboarding',
        follow_up: 'Follow up required',
      },
      tabs: [
        { key: 'all', label: 'All', count: users.length },
        { key: 'active', label: 'Active', count: activeCount },
        { key: 'pending', label: 'Pending', count: pendingCount },
        { key: 'inactive', label: 'Inactive', count: inactiveCount },
      ],
      filters: {
        roles: [
          { label: 'All Roles', value: '' },
          { label: 'Admin', value: 'Admin' },
          { label: 'Manager', value: 'Manager' },
          { label: 'Supervisor', value: 'Supervisor' },
          { label: 'User', value: 'User' },
        ],
        departments: [
          { label: 'All Departments', value: '' },
          { label: 'IT', value: 'IT' },
          { label: 'HR', value: 'HR' },
          { label: 'Finance', value: 'Finance' },
          { label: 'Marketing', value: 'Marketing' },
          { label: 'Sales', value: 'Sales' },
          { label: 'Operation', value: 'Operation' },
          { label: 'Support', value: 'Support' },
        ],
      },
      sortable: ['name', 'email', 'role', 'status', 'joined_at', 'last_activity'],
      pagination: {
        page: 1,
        per_page: 10,
        total: users.length,
        last_page: Math.ceil(users.length / 10),
      },
      users: users,
    },
  };
}

const mockUsersData = generate250Users();
fs.writeFileSync(
  path.join(process.cwd(), 'public', 'mock', 'users.json'),
  JSON.stringify(mockUsersData, null, 2),
  'utf-8'
);
console.log('Finished writing 250 users to public/mock/users.json');
